base/urls.py
from django.urls import path, include
from .views import (
    home_page
)

app_name = 'base'

urlpatterns = [
    path('', home_page, name='home'),
]

crud/urls.py
from django.urls import path, include
from .views import (
    read,
    create,
    update,
    delete,
)

app_name = 'crud'

urlpatterns = [
    path('',         read, name='read'),
    path('create/',  create, name='create'),
    path('update/',  update, name='update'),
    path('delete/',  delete, name='delete'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('action/', include('crud.urls', namespace='crud')),
]

base/models.py
from django.db import models

# Create your models here.

crud/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name    = models.CharField(max_length=100)
    email   = models.EmailField()
    age     = models.IntegerField()

    def __str__(self):
        return self.name

crud/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('name','email','age')
        widgets = {
            'name':forms.TextInput(attrs={'id':'nameId'}),
            'email':forms.EmailInput(attrs={'id':'emailId'}),
            'age':forms.NumberInput(attrs={'id':'ageId'}),
        }

base/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request, 'base/home.html')

crud/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from .models import User
from django.http import JsonResponse

# Create your views here.
def read(request):
    form = UserForm
    users = User.objects.all()

    context = {'form':form, 'users':users}
    return render(request, 'crud/action.html', context)


def create(request):
     if request.method == "POST":
        id = request.POST.get('id')

        if (id == ""):
            form = UserForm(request.POST)
        else:
            user = User.objects.get(pk=id)
            form = UserForm(request.POST, instance=user)
            
        if form.is_valid():
            form.save()
            users = User.objects.values()
            users_data = list(users)
            # print(user_data)
            return JsonResponse({'status':"Saved", 'users_data':users_data})
        else:
            return JsonResponse({'status':0})



def update(request):
    if request.method == "POST":
        pk = request.POST.get('id')
        user = User.objects.get(pk=pk)
        user = {'id':user.id, 'name':user.name, 'email':user.email, 'age':user.age}
        
        return JsonResponse({'status':1, 'user':user})
    else:
        return JsonResponse({'status':0})



def delete(request):
    if request.method == "POST":
        pk = request.POST.get('id')
        user = User.objects.get(pk=pk)
        user.delete()
        users = User.objects.values()
        users_data = list(users)
        return JsonResponse({'status':1, 'users_data':users_data})
    else:
        return JsonResponse({'status':0})

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">

</head>
<body>
        <div class="container-fluid mt-1">
            <a href="{% url 'base:home' %}"><:-Home</a>
        </div>
        <hr>

        {% block main %}{% endblock main %}

        <script src="{% static 'base/js/jquery.js' %}"></script>
        <script src="{% static 'base/js/popper.js' %}"></script>
        <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
        {% include 'crud/ajax.html' %}

</body>
</html>

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block main %}

        <div class="container-fluid">
            <h1>Welcome To Home Page</h1>
            <a href="{% url 'crud:read' %}">Action Page</a>
        </div>

{% endblock main %}

crud/templates/crud/action.html
{% extends 'base/base.html' %}

{% block main %}
    <div class="container-fluid">
        <h4 class="text-center alert alert-danger"> FUNCTION BASED CRUD VIEW USING AJAX</h4>

        <div class="row">
            
            <div class="col-lg-6">
                <form action="" method="POST" novalidate>
                    {% csrf_token %}
                    <input type="hidden" name="stid" id="stId">
                    {{form.as_p}}
                    <input id="btnsave" type="button" value="Save">
                </form>

                <div id="Smsg" class="alert alert-success mt-3" style="width: 50%; display:none;"></div>
                <div id="Emsg" class="alert alert-danger mt-3" style="width: 50%; display:none;"></div>
            </div>

            <div class="col-lg-6">

                <table>
                    <thead>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Age</th>
                        <th>Actions</th>
                    </thead>

                    <tbody id="userData">

                        {% for user in users %}
                            <tr>
                                <td>{{forloop.counter}})</td>
                                <td>{{user.name}}</td>
                                <td>{{user.email}}</td>
                                <td>{{user.age}}</td>
                                <td>
                                    <input type="button" data-sid="{{user.id}}" id="edit" class="btn btn-warning btn-sm" value="Edit">
                                    <input type="button" data-sid="{{user.id}}" id="delete" class="btn btn-danger btn-sm" value="Delete">
                                </td>
                            </tr>   

                        {% endfor %}
                    
                    </tbody>
                                    
                </table>

            </div>

        </div>

    </div>

{% endblock main %}

crud/templates/crud/ajax.html
<script>
$("#btnsave").click(function () {
    console.log("Save button click");
    output    = '';    
    let id    = $('#stId').val();
    let name  = $('#nameId').val();
    let email = $('#emailId').val();
    let age   = $('#ageId').val();
    let csrf  = $("input[name=csrfmiddlewaretoken]").val();

    if (name == "" || email == "" || age == ""){
        //console.log("Please fill all the textboxes");
        $('#Emsg').text("Please fill all the textboxes");
        $('#Emsg').show();
    } else {
            data = {id:id, name:name, email:email, age:age, csrfmiddlewaretoken:csrf};
            $.ajax({
            url: "{% url 'crud:create' %}",
            method: "POST",
            data: data,
            success: function(data){
                //console.log(data);
                x = data.users_data;
                if (data.status == "Saved") {
//                    console.log("Form Submitted Successfully");
                    $('#Smsg').text("Form Submitted Successfully");
                    $('#Smsg').show();

                    for (i=0; i<x.length; i++){
                        output += "<tr>"
                                      +"<td>" + (i+1) +")" +    "</td>"
                                      +"<td>" + x[i].name + "</td>"
                                      +"<td>" + x[i].email + "</td>"
                                      +"<td>" + x[i].age +   "</td>"
                                      +"<td>" 
                                            +"<input type='button' class='btn btn-warning btn-sm' value='Edit' id='edit' data-sid=" + x[i].id +">"
                                            +" <input type='button' class='btn btn-danger btn-sm' value='Delete' id='delete' data-sid=" + x[i].id +">"
                                       +"</td>"
                                   +"</tr>";
                        }

                    $("#userData").html(output);
                    $("#stId").val('');
                    $("form")[0].reset();
                    console.log(data.users_data)
                }else{
                    $('#Emsg').text("Failed To Submit");
                    $('#Emsg').show();
                    //console.log("Failed To Submit");
                }
            },
        });
    }
});

            /// Delete View


$("tbody").on("click", "#delete", function(){
    console.log("Button delete clicked");
    let id = $(this).attr("data-sid");
    let csrf  = $("input[name=csrfmiddlewaretoken]").val();

    //console.log(id);
    data = {id:id, csrfmiddlewaretoken:csrf},
    mythis = this;
    $.ajax({
        url: "{% url 'crud:delete' %}",
        method: "POST",
        data: data,
        success: function(data) {
            if (data.status == 1) {
                console.log("Successfully Deleted");
                $(mythis).closest("tr").fadeOut();
            }else{
                console.log("Failed To Delete");
            }
        },
    });
});

            /// Edit View

$("tbody").on("click", "#edit", function(){
    console.log("Button Edit clicked");
    let id = $(this).attr("data-sid");
    let csrf  = $("input[name=csrfmiddlewaretoken]").val();

    //console.log(id);
    data = {id:id, csrfmiddlewaretoken:csrf};
    $.ajax({
        url: "{% url 'crud:update' %}",
        method: "POST",
        data: data,
        success: function(data) {
            if (data.status == 1) {
                //console.log("Successfully Edited");
                $('#stId').val(data.user.id);
                $('#nameId').val(data.user.name);
                $('#emailId').val(data.user.email);
                $('#ageId').val(data.user.age);

            }else{
                console.log("Failed To Edit");
            }
        },
    });
});

</script>